name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload_results: false
