name: Run Tests With Upload Results

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      upload_results: true
